### ISSUE TITLE
文字変更：空間期間＝共有スペースに変更

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/couple-t-ios#101]
空間期間＝共有スペースに変更

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。新しいバージョンでご確認ください。

**Comment by take-iwa** [comment]
@alexeypolitov 共有スペースの文言変更ですが、購入時の選択肢も変更お願いします。
細かいとこですみませんが、、、
3日間デザイン空間(¥120)　→　共有スペース３日間(¥120)

**Comment by take-iwa** [comment]
@alexeypolitov 繰り返しになりますが、購入するときの項目名も、
共有スペース〇〇円
となるようにお願いします。
![img_0022](https://user-images.githubusercontent.com/23730555/29149969-6dbe859e-7db2-11e7-9787-9ac872562c7f.PNG)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。最新バージョンでご確認ください
