### ISSUE TITLE
空間期間＝共有スペースが購入できない

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/couple-t-ios#104]
キャンセルの文字しか出てこない
![2017-05-25 21 55 36](https://cloud.githubusercontent.com/assets/17405609/26475027/e363f648-41ef-11e7-8c8c-b828d9508a24.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。新しいバージョンでご確認ください。

**Comment by take-iwa** [comment]
できました。OK。
