### ISSUE TITLE
自分で購入した時に、購入の名前を入れているにも関わらずニックネームになる、

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/couple-t-ios#105]
自分で購入した時に、購入の名前を入れているにも関わらず管理画面側でニックネームになる

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。新しいバージョンでご確認ください。

**Comment by take-iwa** [comment]
管理画面確認しました。名前になってます。
