### ISSUE TITLE
tkephoto pickfileに日本語に

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/couple-t-ios#106]
プロフィールの写真のところで

take photo 写真を撮る
pick file   画像を選ぶ

に変更してください。

**Comment by alexeypolitov** [comment]
@tomoyuki1110 新しいバージョンでこちらとなります。

![img_0670](https://cloud.githubusercontent.com/assets/3468058/26564584/be342f9c-451d-11e7-8f6a-8b9e1b0d9f56.PNG)
