### ISSUE TITLE
デザイン　筆ツール　太さ設定のスライダが指と逆に動く

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#107]
太さのが変わる方向もアイコンと逆。

**Comment by alexeypolitov** [comment]
@take-iwa 確認しました。左は細い、右は太いとなります。動画とかアップしていただけますか？

**Comment by take-iwa** [comment]
動画あげてみました。
[IMG_0359.zip](https://github.com/DecodeLLC/couple-t-ios/files/1037064/IMG_0359.zip)

**Comment by take-iwa** [comment]
@alexeypolitov 動画確認できましたでしょうか？進行中でしょうか？

**Comment by take-iwa** [comment]
@alexeypolitov この問題ですが、端末によって表示が異なるようです。
iPhone6s plue は大丈夫でした。
問題が出たのが、iPhone5 と 6 です。
↓iPhone5
![iphone_5](https://user-images.githubusercontent.com/23730555/27944733-c7ebbd88-6323-11e7-8f47-1f6861e0a124.PNG)

↓iPhone6
![iphone_6](https://user-images.githubusercontent.com/23730555/27944732-c7c6e6b6-6323-11e7-92fa-bebbb5982abf.PNG)

↓iPhone6s Plus
![iphone_6s_plus](https://user-images.githubusercontent.com/23730555/27944731-c7c21ca8-6323-11e7-974d-6688477c3fb0.PNG)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。TestFilghtのバージョンをご確認下さい。

**Comment by take-iwa** [comment]
本番ver1.0.6(4)にて、修正確認しました。
