### ISSUE TITLE
共有スペース　複数人で同時に同じテキストを編集すると表示がおかしくなる

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#111]
同時編集時の排他処理どうしているのか？

**Comment by alexeypolitov** [comment]
@take-iwa 同じテキストは同時変更する場合は表示おかしくなるのは仕方ないと思います

**Comment by take-iwa** [comment]
@alexeypolitov 確かに仕方ないところですね。このissueは、クローズします。
