### ISSUE TITLE
招待された側の共有スペースの削除ができない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#112]
招待した側でデザイン(共有スペース)を削除した時、招待された側でデザインが削除されないし、削除できない。

**Comment by alexeypolitov** [comment]
@take-iwa スペースに入って、ユーザーの一覧で「退会」を選べば削除されます

**Comment by take-iwa** [comment]
開き直したら、ちゃんと招待された側でも消えてました。大丈夫です。
