### ISSUE TITLE
カート　注文確定した後もカート内にアイテムが残る

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#113]
そのアイテムをカート内で「注文削除」で消しても
注文履歴には「決済待ち」などのステータスのまま存在するため、
お客さんから「キャンセルしたと思ったのに・・・」とか苦情がきそう。

アプリからのキャンセルはできない仕様？

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください。

**Comment by take-iwa** [comment]
すみません。自分の書き方がよくなかったと思うのですが、
そもそも注文確定した時にカートに残っていることが変かなと思います。
なので、注文確定した場合は、カートから削除し、注文履歴だけに入るようにできますでしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa 支払いが終わるまでにカートに残すのは仕様です

**Comment by take-iwa** [comment]
@alexeypolitov そういう仕様であれば、問題ないです。
ちなみに、相手に注文した場合、カートにはあって注文履歴には入らないのはバグでしょうか？仕様でしょうか？

**Comment by alexeypolitov** [comment]
@take-iwa 仕様です。支払い完了になった場合は相手のカートで現れて、それから相手も注文履歴に残ります

**Comment by take-iwa** [comment]
@alexeypolitov 理解しました。相手はカートに入ったアイテムを選択して必要事項を入力するということですね。ありがとうございます。クローズします。
