### ISSUE TITLE
カート　注文を保存してカートに入れた時、削除できない。

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#114]
確定するしかなく、消すことができない。

**Comment by alexeypolitov** [comment]
注文の下で削除ボタンがあります

**Comment by take-iwa** [comment]
デザインから「注文する」 ー＞ 「キャンセル」選択時に「保存する」を選択 ー＞ 「カート」　に行き注文情報を開いたときに、この画面になります。
名前などの入力はしていない状態です。ここで削除ができないでしょうか？
![img_0005](https://cloud.githubusercontent.com/assets/23730555/26565594/6cdf27b4-4527-11e7-8173-e9e0b03c885c.PNG)

**Comment by alexeypolitov** [comment]
@take-iwa キャンセルを押して、保存しないを選んでください。それか一覧でスワイプしてみてください

**Comment by take-iwa** [comment]
@alexeypolitov 一覧でスワップ！なるほど！できました！・・・これ気づくかな。どこかに説明欲しいですね。FAQに入れときます。

**Comment by take-iwa** [comment]
これは解決済みでした。クローズします。
