### ISSUE TITLE
その他＞問い合わせ　カテゴリ一覧の内容を本番用に

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#117]
問い合わせカテゴリ不備があれば、お願いします。
　・このアプリについて
　・「探す」の機能について
　・デザインツールについて
　・ご注文内容について
　・納期について
　・CPについて
　・著作権について
　・アプリバグ報告
　・その他

**Comment by alexeypolitov** [comment]
@take-iwa カテゴリは管理画面で変更できます

**Comment by take-iwa** [comment]
@alexeypolitov 管理画面教えてください。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
すみません。管理画面確認してたのに、変更するの忘れてました。編集ありがとうございます。
