### ISSUE TITLE
アプリからの問い合わせメールにカテゴリを含めてほしい

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#120]
せっかく問い合わせのカテゴリを作ったので、メールの内容にカテゴリを追加してほしいです。

Category: カテゴリ
User: user@example.com
Content: 問い合わせ内容の文章

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。TestFilghtのバージョンをご確認下さい。

**Comment by take-iwa** [comment]
開発環境で確認できました。

**Comment by take-iwa** [comment]
本番1.0.6(4)にて、確認しました。
