### ISSUE TITLE
新規登録した際にエラーが出る

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#121]
リストにないメールアドレスで登録しているはずが、以下のようなエラーが出ます。
しかも、エラーが出ているにもかかわらず、ちゃんと登録できています。
混乱するので、修正お願いします。
![img_0002](https://user-images.githubusercontent.com/23730555/27175595-99dcf0b8-51fa-11e7-9635-ff90fe731e38.PNG)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。TestFilghtのバージョンをご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov TestFlightで問題なく登録できました。

**Comment by take-iwa** [comment]
本番1.0.6(4)にて、問題なく登録できました。
