### ISSUE TITLE
ユーザー検索でログインしているユーザーが上に表示されるように

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#122]
検索項目にオンラインフィルターがありますが、
デフォルトでオンラインのユーザーを最初に表示するようにしでください。
これは、アンドロイド版でも同じです。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。TestFilghtのバージョンをご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov 本番1.0.6(4)にて確認しました。
