### ISSUE TITLE
プロフィールで性別、年齢(年代)を入力必須項目にする

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#123]
最初のプロフィール入力で性別と年齢を入力必須にしてください。

加えて、プロフィール画像ですが、アップロード以外に
プリセットで女性用と男性用それぞれ10種類ずつ用意して
選択できるようにお願いします。

**Comment by tomoyuki1110** [comment]
プロフィール入力というか、最初の登録の時です。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。TestFilghtのバージョンをご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov TestFlightで確認できました！

**Comment by take-iwa** [comment]
本番1.0.6(4)にて、登録時の入力確認しました。
