### ISSUE TITLE
一覧ページで各個人の性別と年齢がわかるように

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/couple-t-ios#125]
![screenshot_20170729-214717](https://user-images.githubusercontent.com/17405609/28744950-d457ea5c-74a7-11e7-8d88-50fe13265143.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。TestFilghtのバージョンをご確認下さい。

**Comment by take-iwa** [comment]
@alexeypolitov TestFlightで年齢、性別登録しているユーザーは一覧で確認できました。

**Comment by take-iwa** [comment]
本番1.0.6(4)で性別・年齢表示されるの確認しました。
