### ISSUE TITLE
注文確定後,カート内で注文を取り消せてしまう

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-ios#127]
これは、アンドロイドでも同じです。

注文確定後もカート内にあるために、生産中になったとしてもアプリから注文を取り消せてしまう。

下の画面から注文完了したら、カートから消して注文履歴のみで表示してほしいです。

![img_0026](https://user-images.githubusercontent.com/23730555/29450617-53786c20-843a-11e7-9905-90b39d00a25a.PNG)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ロジクの問題であれば相談させてください

**Comment by take-iwa** [comment]
@alexeypolitov TestFlight v1.0.8(1)で確認しました。
注文確定してもまだカートに入っており、横にスワップすると注文データが消えてしまいます。
確認お願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 注文確定って銀行それともカードですか？

**Comment by alexeypolitov** [comment]
@take-iwa カートに入ってるまだ注文確定してないとういう意味です。詳しく情報教えていただけますか？

**Comment by take-iwa** [comment]
@alexeypolitov 銀行振込で確認してました。

注文確定というのは、printtyにアップロードしたら「確定」でしょうか？
振込を確認して、adminで決済完了したら「確定」でしょうか？


確認した流れはこちら。

自分あてに銀行振込で購入
　　　>>　カートに入る。ステータス「決済待ち」。スワップで消せる。
↓
admin画面でステータス「決済完了」に変更
　　　>>　アプリに通知。
　　　　　**☆この時点でまだカートにある。スワップで消せる**

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
